fos_rest:
    view:
      formats: { json: true, xml: false, rss: false }
      default_engine: twig
      view_response_listener: true
      mime_types:
        json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    serializer:
      serialize_null: true
    body_converter:
      enabled: true
      validate: true
      validation_errors_argument: violations
    format_listener:
      # change rules /login -> /'home'
      rules:
        - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    exception:
      enabled: true
      exception_controller: 'fos_rest.exception.controller:showAction'
    versioning:
      enabled: true
      resolvers:
        media_type:
          enabled: true
          regex: '/(v|version)=(?P<version>[0-9\.]+)/'