framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    serializer:
        enabled: true

    validation: { enable_annotations: true }

    property_info:
        enabled: true